# Generated by Django 3.2 on 2021-04-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_auto_20210411_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
