# Generated by Django 3.2 on 2021-04-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_alter_translate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='sentence',
            field=models.TextField(verbose_name='sentence'),
        ),
    ]
